name: simple_grouped_listview
description: |
  A package to display a grouped list of items. Provide a List, a grouper, and let it display it as a ListView, a GridView or anything else. Grouped by headers.

homepage: https://github.com/quentin7b/flutter_grouped_listview
repository: https://github.com/quentin7b/flutter_grouped_listview
issue_tracker: https://github.com/quentin7b/flutter_grouped_listview/issues

version: 1.0.0
publish_to: 

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
