name: Publish package to Pub.dev

on: 
  push:
    tags:
    - '*'

jobs:
  publishing:
    name: Create and deploy the package to pub dev
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
